/*
 * PROBLEM 2: Even Fibonacci Numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
 */

function main(number: number): number {
  return getNextFibonacci(1, 2, number, 0);
}

function getNextFibonacci(
  prevNum: number,
  currNumber: number,
  maxNum: number,
  currentEvenNumber: number,
): number {
  if (currNumber > maxNum) return currentEvenNumber;

  if (currNumber % 2 === 0) {
    currentEvenNumber += currNumber;
  }

  return getNextFibonacci(
    currNumber,
    prevNum + currNumber,
    maxNum,
    currentEvenNumber,
  );
}

export default main;
